# TCL File Generated by Component Editor 23.1
# Wed May 17 14:59:30 BST 2023
# DO NOT MODIFY


# 
# telemetry_test "Telemetry Test for BMC SPI Interface" v1.0
#  2023.05.17.14:59:30
# Telemetry Test for BMC SPI Interface
# 

# 
# request TCL package from ACDS 23.1
# 
package require -exact qsys 23.1


# 
# module telemetry_test
# 
set_module_property DESCRIPTION "Telemetry Test for BMC SPI Interface"
set_module_property NAME telemetry_test
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Telemetry Test Registers"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL telemetry_test
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file telemetry_test.vhd VHDL PATH ../rtl/telemetry_test.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter QSFPDD_NUM INTEGER 1 "Number of QSFPDD Modules in design"
set_parameter_property QSFPDD_NUM DEFAULT_VALUE 1
set_parameter_property QSFPDD_NUM DISPLAY_NAME "Number of QSFPDD Modules"
set_parameter_property QSFPDD_NUM UNITS None
set_parameter_property QSFPDD_NUM ALLOWED_RANGES 1:3
set_parameter_property QSFPDD_NUM DESCRIPTION "Number of modules in design"
set_parameter_property QSFPDD_NUM AFFECTS_GENERATION false
set_parameter_property QSFPDD_NUM HDL_PARAMETER true
set_parameter_property QSFPDD_NUM EXPORT true


# 
# display items
# 


# 
# connection point aclk
# 
add_interface aclk clock end
set_interface_property aclk ENABLED true
set_interface_property aclk EXPORT_OF ""
set_interface_property aclk PORT_NAME_MAP ""
set_interface_property aclk CMSIS_SVD_VARIABLES ""
set_interface_property aclk SVD_ADDRESS_GROUP ""
set_interface_property aclk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property aclk SV_INTERFACE_TYPE ""
set_interface_property aclk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port aclk aclk clk Input 1


# 
# connection point areset
# 
add_interface areset reset end
set_interface_property areset associatedClock aclk
set_interface_property areset synchronousEdges DEASSERT
set_interface_property areset ENABLED true
set_interface_property areset EXPORT_OF ""
set_interface_property areset PORT_NAME_MAP ""
set_interface_property areset CMSIS_SVD_VARIABLES ""
set_interface_property areset SVD_ADDRESS_GROUP ""
set_interface_property areset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property areset SV_INTERFACE_TYPE ""
set_interface_property areset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port areset areset reset Input 1

# 
# connection point axi
# 
add_interface axi axi4lite end
set_interface_property axi associatedClock aclk
set_interface_property axi associatedReset areset
set_interface_property axi readAcceptanceCapability 1
set_interface_property axi writeAcceptanceCapability 1
set_interface_property axi combinedAcceptanceCapability 1
set_interface_property axi bridgesToMaster ""
set_interface_property axi ENABLED true
set_interface_property axi EXPORT_OF ""
set_interface_property axi PORT_NAME_MAP ""
set_interface_property axi CMSIS_SVD_VARIABLES ""
set_interface_property axi SVD_ADDRESS_GROUP ""
set_interface_property axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi SV_INTERFACE_TYPE ""
set_interface_property axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi awaddr awaddr Input 12
add_interface_port axi awvalid awvalid Input 1
add_interface_port axi awready awready Output 1
add_interface_port axi wdata wdata Input 32
add_interface_port axi wstrb wstrb Input 4
add_interface_port axi wvalid wvalid Input 1
add_interface_port axi wready wready Output 1
add_interface_port axi bresp bresp Output 2
add_interface_port axi bvalid bvalid Output 1
add_interface_port axi bready bready Input 1
add_interface_port axi araddr araddr Input 12
add_interface_port axi arvalid arvalid Input 1
add_interface_port axi arready arready Output 1
add_interface_port axi rdata rdata Output 32
add_interface_port axi rresp rresp Output 2
add_interface_port axi rvalid rvalid Output 1
add_interface_port axi rready rready Input 1
add_interface_port axi awprot awprot Input 3
add_interface_port axi arprot arprot Input 3

# 
# connection point eeprom
# 
add_interface eeprom conduit end
set_interface_property eeprom associatedClock aclk
set_interface_property eeprom associatedReset areset
set_interface_property eeprom ENABLED true
set_interface_property eeprom EXPORT_OF ""
set_interface_property eeprom PORT_NAME_MAP ""
set_interface_property eeprom CMSIS_SVD_VARIABLES ""
set_interface_property eeprom SVD_ADDRESS_GROUP ""
set_interface_property eeprom IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property eeprom SV_INTERFACE_TYPE ""
set_interface_property eeprom SV_INTERFACE_MODPORT_TYPE ""

add_interface_port eeprom eeprom_data data Input 2048


# 
# connection point qspfdd0_ctrl_status
# 
add_interface qspfdd0_ctrl_status conduit end
set_interface_property qspfdd0_ctrl_status associatedClock aclk
set_interface_property qspfdd0_ctrl_status associatedReset areset
set_interface_property qspfdd0_ctrl_status ENABLED true
set_interface_property qspfdd0_ctrl_status EXPORT_OF ""
set_interface_property qspfdd0_ctrl_status PORT_NAME_MAP ""
set_interface_property qspfdd0_ctrl_status CMSIS_SVD_VARIABLES ""
set_interface_property qspfdd0_ctrl_status SVD_ADDRESS_GROUP ""
set_interface_property qspfdd0_ctrl_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property qspfdd0_ctrl_status SV_INTERFACE_TYPE ""
set_interface_property qspfdd0_ctrl_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port qspfdd0_ctrl_status qsfpdd0_rst_n rst_n Output 1
add_interface_port qspfdd0_ctrl_status qsfpdd0_lpmode lpmode Output 1
add_interface_port qspfdd0_ctrl_status qsfpdd0_int_n int_n Input 1
add_interface_port qspfdd0_ctrl_status qsfpdd0_present_n present_n Input 1

# 
# connection point qspfdd1_ctrl_status
# 
add_interface qspfdd1_ctrl_status conduit end
set_interface_property qspfdd1_ctrl_status associatedClock aclk
set_interface_property qspfdd1_ctrl_status associatedReset areset
set_interface_property qspfdd1_ctrl_status ENABLED true
set_interface_property qspfdd1_ctrl_status EXPORT_OF ""
set_interface_property qspfdd1_ctrl_status PORT_NAME_MAP ""
set_interface_property qspfdd1_ctrl_status CMSIS_SVD_VARIABLES ""
set_interface_property qspfdd1_ctrl_status SVD_ADDRESS_GROUP ""
set_interface_property qspfdd1_ctrl_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property qspfdd1_ctrl_status SV_INTERFACE_TYPE ""
set_interface_property qspfdd1_ctrl_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port qspfdd1_ctrl_status qsfpdd1_rst_n rst_n Output 1
add_interface_port qspfdd1_ctrl_status qsfpdd1_lpmode lpmode Output 1
add_interface_port qspfdd1_ctrl_status qsfpdd1_int_n int_n Input 1
add_interface_port qspfdd1_ctrl_status qsfpdd1_present_n present_n Input 1

# 
# connection point qspfdd2_ctrl_status
# 
add_interface qspfdd2_ctrl_status conduit end
set_interface_property qspfdd2_ctrl_status associatedClock aclk
set_interface_property qspfdd2_ctrl_status associatedReset areset
set_interface_property qspfdd2_ctrl_status ENABLED true
set_interface_property qspfdd2_ctrl_status EXPORT_OF ""
set_interface_property qspfdd2_ctrl_status PORT_NAME_MAP ""
set_interface_property qspfdd2_ctrl_status CMSIS_SVD_VARIABLES ""
set_interface_property qspfdd2_ctrl_status SVD_ADDRESS_GROUP ""
set_interface_property qspfdd2_ctrl_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property qspfdd2_ctrl_status SV_INTERFACE_TYPE ""
set_interface_property qspfdd2_ctrl_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port qspfdd2_ctrl_status qsfpdd2_rst_n rst_n Output 1
add_interface_port qspfdd2_ctrl_status qsfpdd2_lpmode lpmode Output 1
add_interface_port qspfdd2_ctrl_status qsfpdd2_int_n int_n Input 1
add_interface_port qspfdd2_ctrl_status qsfpdd2_present_n present_n Input 1