# TCL File Generated by Component Editor 23.3
# Fri Nov 17 17:44:31 GMT 2023
# DO NOT MODIFY


# 
# powerburner_ip "PowerBurner IP" v0.1
# BittWare 2023.11.17.17:44:31
# Configurable PowerBurner IP
# 

# 
# request TCL package from ACDS 23.3
# 
package require -exact qsys 23.3


# 
# module powerburner_ip
# 
set_module_property DESCRIPTION "Configurable PowerBurner IP"
set_module_property NAME powerburner_ip
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR BittWare
set_module_property DISPLAY_NAME "PowerBurner IP"
set_module_property DATASHEET_URL false
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL powerburner_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file powerburner_controller.vhd VHDL PATH ../rtl/powerburner_controller.vhd TOP_LEVEL_FILE
add_fileset_file bram_cook_test.vhd VHDL PATH ../rtl/bram_cook_test.vhd
add_fileset_file dsp_cook_test.vhd VHDL PATH ../rtl/dsp_cook_test.vhd
add_fileset_file powerburner.vhd VHDL PATH ../rtl/powerburner.vhd
add_fileset_file sreg_cook_test.vhd VHDL PATH ../rtl/sreg_cook_test.vhd
add_fileset_file dprw_ram.vhd VHDL PATH ../rtl/dprw_ram.vhd
add_fileset_file general_fifo.vhd VHDL PATH ../rtl/general_fifo.vhd


# 
# documentation links
# 


#
# parameters
# 
add_parameter CORE_CLK_FREQUENCY NATURAL 100000000 "Frequency of the external core input clock, in Hz, passed to the PowerBurner IP through the pb_clk port"
set_parameter_property CORE_CLK_FREQUENCY DEFAULT_VALUE 100000000
set_parameter_property CORE_CLK_FREQUENCY DISPLAY_NAME "Core Clock Frequency (Hz)"
set_parameter_property CORE_CLK_FREQUENCY UNITS None
set_parameter_property CORE_CLK_FREQUENCY ALLOWED_RANGES 0:2147483647
set_parameter_property CORE_CLK_FREQUENCY DESCRIPTION "Frequency of the external core input clock, in Hz, passed to the PowerBurner IP through the pb_clk port"
set_parameter_property CORE_CLK_FREQUENCY AFFECTS_GENERATION false
set_parameter_property CORE_CLK_FREQUENCY HDL_PARAMETER true
set_parameter_property CORE_CLK_FREQUENCY EXPORT true
add_parameter POWERBURNER_INSTANCES INTEGER 1 "Quantity of Powerburner blocks instantiated within the PowerBurner IP. Valid range: 1 to 32"
set_parameter_property POWERBURNER_INSTANCES DEFAULT_VALUE 1
set_parameter_property POWERBURNER_INSTANCES DISPLAY_NAME "PowerBurner Instances"
set_parameter_property POWERBURNER_INSTANCES WIDTH ""
set_parameter_property POWERBURNER_INSTANCES UNITS None
set_parameter_property POWERBURNER_INSTANCES ALLOWED_RANGES 1:32
set_parameter_property POWERBURNER_INSTANCES DESCRIPTION "Quantity of Powerburner blocks instantiated within the PowerBurner IP. Valid range: 1 to 32"
set_parameter_property POWERBURNER_INSTANCES AFFECTS_GENERATION false
set_parameter_property POWERBURNER_INSTANCES HDL_PARAMETER true
set_parameter_property POWERBURNER_INSTANCES EXPORT true
add_parameter BRAM_HW_TARGET NATURAL 16 "Quantity of BRAMs utilised after compilation for the device. This value must be a min: 16*instances"
set_parameter_property BRAM_HW_TARGET DEFAULT_VALUE 16
set_parameter_property BRAM_HW_TARGET DISPLAY_NAME "BRAM Utilisation"
set_parameter_property BRAM_HW_TARGET UNITS None
set_parameter_property BRAM_HW_TARGET ALLOWED_RANGES 16:2147483647
set_parameter_property BRAM_HW_TARGET DESCRIPTION "Quantity of BRAMs utilised after compilation for the device. This value must be a min: 16*instances"
set_parameter_property BRAM_HW_TARGET AFFECTS_GENERATION false
set_parameter_property BRAM_HW_TARGET HDL_PARAMETER true
set_parameter_property BRAM_HW_TARGET EXPORT true
add_parameter SREG_HW_TARGET NATURAL 64 "Quantity of REGs utilised after compilation for the device. This value must be a min: 64*instances"
set_parameter_property SREG_HW_TARGET DEFAULT_VALUE 64
set_parameter_property SREG_HW_TARGET DISPLAY_NAME "SREG Utilisation"
set_parameter_property SREG_HW_TARGET UNITS None
set_parameter_property SREG_HW_TARGET ALLOWED_RANGES 64:2147483647
set_parameter_property SREG_HW_TARGET DESCRIPTION "Quantity of REGs utilised after compilation for the device. This value must be a min: 64*instances"
set_parameter_property SREG_HW_TARGET AFFECTS_GENERATION false
set_parameter_property SREG_HW_TARGET HDL_PARAMETER true
set_parameter_property SREG_HW_TARGET EXPORT true
add_parameter DSP_HW_TARGET NATURAL 8 "Quantity of DSPs utilised after compilation for the device. This value must be a min: 4*instances"
set_parameter_property DSP_HW_TARGET DEFAULT_VALUE 8
set_parameter_property DSP_HW_TARGET DISPLAY_NAME "DSP Utilisation"
set_parameter_property DSP_HW_TARGET UNITS None
set_parameter_property DSP_HW_TARGET ALLOWED_RANGES 8:2147483647
set_parameter_property DSP_HW_TARGET DESCRIPTION "Quantity of DSPs utilised after compilation for the device. This value must be a min: 4*instances"
set_parameter_property DSP_HW_TARGET AFFECTS_GENERATION false
set_parameter_property DSP_HW_TARGET HDL_PARAMETER true
set_parameter_property DSP_HW_TARGET EXPORT true


# 
# display items
# 
add_display_item "" "Top-Level Settings" GROUP ""
add_display_item "" "PowerBurner Instance Settings" GROUP ""
add_display_item "Top-Level Settings" "Core Clock Frequency (Hz)" PARAMETER ""
add_display_item "Top-Level Settings" "PowerBurner Instantiations" PARAMETER ""
add_display_item "Hardware Targets" BRAM_HW_TARGET PARAMETER ""
add_display_item "Hardware Targets" SREG_HW_TARGET PARAMETER ""
add_display_item "Hardware Targets" DSP_HW_TARGET PARAMETER ""
add_display_item "Top-Level Settings" "Core Clock Frequency (Hz)" PARAMETER ""
add_display_item "Top-Level Settings" "PowerBurner Instantiations" PARAMETER ""
add_display_item "Utilisation Target" BRAM_HW_TARGET PARAMETER ""
add_display_item "Utilisation Target" SREG_HW_TARGET PARAMETER ""
add_display_item "Utilisation Target" DSP_HW_TARGET PARAMETER ""


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clk
set_interface_property altera_axi4lite_slave associatedReset reset
set_interface_property altera_axi4lite_slave wakeupSignals false
set_interface_property altera_axi4lite_slave uniqueIdSupport false
set_interface_property altera_axi4lite_slave poison false
set_interface_property altera_axi4lite_slave traceSignals false
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave dfhFeatureGuid 0
set_interface_property altera_axi4lite_slave dfhGroupId 0
set_interface_property altera_axi4lite_slave dfhParameterId ""
set_interface_property altera_axi4lite_slave dfhParameterName ""
set_interface_property altera_axi4lite_slave dfhParameterVersion ""
set_interface_property altera_axi4lite_slave dfhParameterData ""
set_interface_property altera_axi4lite_slave dfhParameterDataLength ""
set_interface_property altera_axi4lite_slave dfhFeatureMajorVersion 0
set_interface_property altera_axi4lite_slave dfhFeatureMinorVersion 0
set_interface_property altera_axi4lite_slave dfhFeatureId 35
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""
set_interface_property altera_axi4lite_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property altera_axi4lite_slave SV_INTERFACE_TYPE ""
set_interface_property altera_axi4lite_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port altera_axi4lite_slave awaddr awaddr Input 8
add_interface_port altera_axi4lite_slave awvalid awvalid Input 1
add_interface_port altera_axi4lite_slave awready awready Output 1
add_interface_port altera_axi4lite_slave awprot awprot Input 3
add_interface_port altera_axi4lite_slave wdata wdata Input 32
add_interface_port altera_axi4lite_slave wstrb wstrb Input 4
add_interface_port altera_axi4lite_slave wvalid wvalid Input 1
add_interface_port altera_axi4lite_slave wready wready Output 1
add_interface_port altera_axi4lite_slave bresp bresp Output 2
add_interface_port altera_axi4lite_slave bvalid bvalid Output 1
add_interface_port altera_axi4lite_slave bready bready Input 1
add_interface_port altera_axi4lite_slave araddr araddr Input 8
add_interface_port altera_axi4lite_slave arvalid arvalid Input 1
add_interface_port altera_axi4lite_slave arready arready Output 1
add_interface_port altera_axi4lite_slave arprot arprot Input 3
add_interface_port altera_axi4lite_slave rdata rdata Output 32
add_interface_port altera_axi4lite_slave rresp rresp Output 2
add_interface_port altera_axi4lite_slave rvalid rvalid Output 1
add_interface_port altera_axi4lite_slave rready rready Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk SV_INTERFACE_TYPE ""
set_interface_property clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk aclk clk Input 1


# 
# connection point pb_clk
# 
add_interface pb_clk clock end
set_interface_property pb_clk ENABLED true
set_interface_property pb_clk EXPORT_OF ""
set_interface_property pb_clk PORT_NAME_MAP ""
set_interface_property pb_clk CMSIS_SVD_VARIABLES ""
set_interface_property pb_clk SVD_ADDRESS_GROUP ""
set_interface_property pb_clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property pb_clk SV_INTERFACE_TYPE ""
set_interface_property pb_clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port pb_clk pb_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset areset reset Input 1

